#!/bin/bash

mkdir -p "${HOME}/.log"

alias start='cygstart'
alias open='cygstart'
alias edit='cygstart -e'
alias explore='cygstart -x'

alias ifconfig='ipconfig'

export TMPDIR='/var/tmp'
export CYGWIN="nodosfilewarning"
#export LESS='srC'
export JAVA_HOME="/usr/local/java"
export GROOVY_HOME="/usr/local/groovy"
export CLASSPATH="$CLASSPATH:."
export ANT_HOME="/usr/local/ant"
export MPLAYER="/usr/local/mplayer"
export PYTIVO="/usr/local/pytivo"
export ANDROID_PATH="/Users/smartin/AppData/Local/Android/sdk"
export ANDROID_HOME='C:\Users\smartin\AppData\Local\Android\sdk'
export NODE_MODULES="$HOME/node_modules"

export FFMPEG_PATH="/usr/local/ffmpeg"
export MPLAYER_PATH="/usr/local/mplayer"
export GOROOT="C:\cygwin64\usr\local\go-windows-amd64-bootstrap"
export GOPATH="C:\cygwin64\home\smartin\src\gocode"

# Create my personal Log directory
export LOG_DIR=${HOME}/.log
/usr/bin/mkdir -p $LOG_DIR

# Adding Microsoft.NET to path
DOTNET=$(/usr/bin/ls -rt /c/Windows/Microsoft.NET/Framework64 | /bin/tail -1)
PATH="/c/Windows/Microsoft.NET/Framework64/${DOTNET}:${PATH}"

# Adding NodeJS variables:
# source "/d/Apps/nodejs/nv" > /dev/null 2>&1

# The global environment variable doesn't work for this:
export SVN_SSH="/bin/ssh -q"

# Don't put duplicate lines in the history.
export HISTSIZE=5000
export HISTFILESIZE=${HISTSIZE}
export HISTCONTROL='erasedups:ignoreboth'
export HISTTIMEFORMAT="%m/%d/%y %T "
export HISTIGNORE="&:[ ]*:exit"

# Prefer English UTF-8
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

export MANPAGER="less -X"

# Establish Ruby's documenter uses Ansi formatting:
export RI='-f ansi'

export TMOUT=0

pathmunge() {
  # If the new directory is already in our PATH skip it
  case "$:${PATH}:" in
    *:"$1":*)
      ;;
    *)
      if [ "$2" == "after" ];then
        PATH="$PATH:$(/bin/cygpath $1)"
      else
        PATH="$(/bin/cygpath $1):$PATH"
      fi
  esac
}

# Inserted before current path
# So last one ends up being first on PATH
for var in "$JAVA_HOME" "$ANT_HOME" "$HOME" "$GOROOT" "$GOPATH"
do
  if [ -d "${var}/bin" -a -r "${var}/bin" ];then
    pathmunge "${var}/bin"
  fi
done

# Add these after the rest of the PATH
for var in "$GROOVY_HOME" "$MYSQL_HOME"
do
  if [ -d "${var}/bin" -a -r "${var}/bin" ];then
    pathmunge "${var}/bin" after
  fi
done
pathmunge /sbin after
pathmunge /usr/sbin after

HAVE_VIM=$(command -v vim)

EDITOR=vi
if [ -n "$HAVE_VIM" ];then
  EDITOR="$HAVE_VIM"
fi
export EDITOR

# unset pathmunge
