#!/bin/bash

alias ff='_ff'
alias ffd='_ffd'
alias ffl='_ffl'
alias ffn='_ffn'
alias vif='_vif'
alias grepr="_grepr"
alias greprl="_greprl"
alias greplr="_greprl"
alias grepri="_grepri"
alias grepir="_grepri"
alias grepril="_grepril"
alias greprli="_grepril"

_grepr() {
  grep --exclude-dir target --exclude-dir vendor --exclude-dir .git -r "$*" .
}

_greprl() {
  grep --exclude-dir target --exclude-dir vendor --exclude-dir .git -rl "$*" .
}

_grepri() {
  grep --exclude-dir target --exclude-dir vendor --exclude-dir .git -ri "$*" .
}

_grepril() {
  grep --exclude-dir target --exclude-dir vendor --exclude-dir .git -ril "$*" .
}

_ff() {
    if [ $# -eq 0 ];then
        FF_DIR="."
    else
        FF_DIR="$1"
    fi
    find "${FF_DIR}" -type f
}

_ffd() {
    if [ $# -eq 0 ];then
        FF_DIR="."
    else
        FF_DIR="$1"
    fi
    find "${FF_DIR}" -type d
}

_ffl() {
    if [ $# -eq 0 ];then
        FF_DIR="."
    else
        FF_DIR="$1"
    fi
    find "${FF_DIR}" -type f -ls
}

_ffn() {
    find . -type f -name "$1"
}

# shellcheck disable=SC2046
_vif() {
  vi $(find . -name "$1")
}
