#!/bin/bash

mkdir -p "$HOME/.history"

alias h="_h"

# Store lots of history to go back in time
export HISTSIZE=10000
# And file size stored
export HISTFILESIZE=${HISTSIZE}
export HISTCONTROL='erasedups:ignoreboth'
export HISTIGNORE="h:history:ls:ps:ll:exit"
# Do the 'Are you sure' thing like ZSH
shopt -s histverify

shopt -s histreedit
shopt -s histappend

# Read from the central history file: ~/.bash_history
#builtin history -c && builtin history -r

# Change to specific history file
TTY="$(basename $(tty))"
export tmpHISTFILE="$HOME/.history/history_session.$TTY"
\cp -f "$HOME/.bash_history" "$tmpHISTFILE"
export HISTFILE="$HOME/.history/history_session.$TTY"
builtin history -c
builtin history -r

# Write our data to that
# history -a

_bash_history_sync() {
  builtin history -a
  HISTFILESIZE=$HISTSIZE
  builtin history -c
  builtin history -r
}

history() {
  _bash_history_sync
  builtin history "$@"
}

export PROMPT_COMMAND="_bash_history_sync;$PROMPT_COMMAND"

_h () {
    if [ $# -gt 0 ]; then
        history | grep -i "$*"
    else
        history
    fi
}
