#!/bin/bash

alias psg='_psg'
alias psgc='_psgc'
alias psl='_psl'
alias psn='_psn'
alias psw='tasklist'

_psg() {
    ps auxw | grep -i "$*" | grep -v grep
}

_psgc() {
    ps auxw | /usr/bin/grep -i "$*" | grep -v grep
}

_psl() {
    tasklist /v | grep -i "$*"
}


_psn() {
    tasklist | sed 's/,//g' | sort --sort=h -k 5
}
