#!/bin/bash
# Shell prompt based on the Solarized Dark theme.
# Screenshot: http://i.imgur.com/EkEtphC.png
# Heavily inspired by @necolas’s prompt: https://github.com/necolas/dotfiles
# iTerm → Profiles → Text → use 13pt Monaco with 1.1 vertical spacing.

if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
  export TERM='gnome-256color';
elif infocmp xterm-256color >/dev/null 2>&1; then
  export TERM='xterm-256color';
fi;
declare -i r

IDCMD=$(command -v id)

# KUBE=$(command -v kubectl)
if [ -x "${KUBE}" ];then
  prompt_kube() {
    echo -n "$(kubectl config current-context 2>/dev/null)"
  }
fi

# GIT_PS1_DESCRIBE_STYLE=default
# GIT_PS1_SHOWCOLORHINTS=1
# GIT_PS1_SHOWDIRTYSTATE=1
# GIT_PS1_SHOWSTASHSTATE=1
# GIT_PS1_SHOWUPSTREAM=verbose

if tput setaf 1 &> /dev/null; then
  tput sgr0; # reset colors
  bold=$(tput bold);
  reset=$(tput sgr0);
  # Solarized colors, taken from http://git.io/solarized-colors.
  # black=$(tput setaf 0);
  # blue=$(tput setaf 33);
  # cyan=$(tput setaf 37);
  green=$(tput setaf 64);
  orange=$(tput setaf 166);
  # purple=$(tput setaf 125);
  red=$(tput setaf 124);
  # violet=$(tput setaf 61);
  white=$(tput setaf 15);
  yellow=$(tput setaf 136);
else
  bold='';
  reset="\e[0m";
  # black="\e[1;30m";
  # blue="\e[1;34m";
  # cyan="\e[1;36m";
  green="\e[1;32m";
  orange="\e[1;33m";
  # purple="\e[1;35m";
  red="\e[1;31m";
  # violet="\e[1;35m";
  white="\e[1;37m";
  yellow="\e[1;33m";
fi;

# Highlight the user name when logged in as root.
userStyle="${green}";
userName="${USER}";
if [[ "${USER}" == "root" ]]; then
  userStyle="${red}";
  userName="root";
elif [[ "${UNAME}" == "cygwin" ]];then
  userStyle="${green}";
  userName="${USER}";
  GREP="$(command -v grep)"
  "${IDCMD}" -Gn 2>/dev/null | "${GREP}" -iq admin
  declare -i RETVAL="$?"
  if [ "$RETVAL" -eq 0 ];then
    # Give me a Big Red Admin tag so we know we're running with
    # elevated permissions.
    userStyle="${red}";
    userName='Admin';
  fi
  unset RETVAL
fi;

# Highlight the hostname when connected via SSH.
if [[ "${SSH_TTY}" ]]; then
  hostStyle="${bold}${orange}";
else
  hostStyle="${green}";
fi;

# Set the terminal title to the current working directory.
PS1="\[\033]0;\w\007\]";
PS1+="\[${bold}\]\D{%c}\n"; # newline
PS1+='$(r=$?; test $r -ne 0 && echo "\[\e[1;31m\][ret:$r] ")'
PS1+="\[${userStyle}\]${userName}"; # username
PS1+="\[${white}\]@";
PS1+="\[${hostStyle}\]\h"; # host
PS1+="\[${white}\] in ";
PS1+="\[${green}\]\w"; # working directory
PS1+='$(__git_ps1 " \[${white}\](%s)")'; # Git repository details
if [ -x "${KUBE}" ];then
  PS1+=" \[${yellow}\]KubeCTX: \[${orange}\]\$(prompt_kube)"
fi
PS1+="\n";
PS1+="\[${white}\]\$ \[${reset}\]"; # `$` (and reset color)
export PS1;

PS2="\[${yellow}\]→ \[${reset}\]";
export PS2;
