#!/bin/bash
# Shell prompt based on the Solarized Dark theme.
# Screenshot: http://i.imgur.com/EkEtphC.png
# Heavily inspired by @necolas’s prompt: https://github.com/necolas/dotfiles
# iTerm → Profiles → Text → use 13pt Monaco with 1.1 vertical spacing.

# Only source this file one time
[[ -z "${BASH_PROMPT}" ]] && readonly BASH_PROMPT=true || return 0

[[ -f "$HOME/.functions/git-prompt" ]] && source "$HOME/.functions/git-prompt"
[[ -f "$HOME/.functions/git-prompt.off" ]] && source "$HOME/.functions/git-prompt.off"

if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
  export TERM='gnome-256color'
elif infocmp xterm-256color >/dev/null 2>&1; then
  export TERM='xterm-256color'
fi
declare -i r

IDCMD=$(command -v id)

GIT_PS1_DESCRIBE_STYLE=default
GIT_PS1_SHOWCOLORHINTS=1
GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWSTASHSTATE=1
GIT_PS1_SHOWUPSTREAM=verbose

if tput setaf 1 &> /dev/null; then
  tput sgr0; # reset colors
  bold=$(tput bold)
  reset=$(tput sgr0)
  # Solarized colors, taken from http://git.io/solarized-colors.
  black=$(tput setaf 0)
  blue=$(tput setaf 33)
  cyan=$(tput setaf 37)
  green=$(tput setaf 64)
  orange=$(tput setaf 166)
  purple=$(tput setaf 125)
  red=$(tput setaf 124)
  violet=$(tput setaf 61)
  white=$(tput setaf 15)
  yellow=$(tput setaf 136)
else
  bold=''
  reset="\e[0m"
  black="\e[1;30m"
  blue="\e[1;34m"
  cyan="\e[1;36m"
  green="\e[1;32m"
  orange="\e[1;33m"
  purple="\e[1;35m"
  red="\e[1;31m"
  violet="\e[1;35m"
  white="\e[1;37m"
  yellow="\e[1;33m"
fi

# Highlight the user name when logged in as root.
userStyle="${orange}"
userName="${USER}"
if [[ "${USER}" == "root" ]]; then
  userStyle="${red}"
  userName="root"
elif [[ "${UNAME}" == "cygwin" ]];then
  userName="${USER}"
  GREP="$(command -v grep)"
  "${IDCMD}" -Gn 2>/dev/null | "${GREP}" -iq admin
  declare -i RETVAL="$?"
  if [ "$RETVAL" -eq 0 ];then
    # Give me a Big Red Admin tag so we know we're running with
    # elevated permissions.
    # For some reason the global value for red is lost here
    # red="\e[1;31m"
    userStyle="${red}"
    userName="ADMIN"
  fi
  unset RETVAL
fi

# Highlight the hostname when connected via SSH.
if [[ "${SSH_TTY}" ]]; then
  hostStyle="${bold}${orange}"
else
  hostStyle="${green}"
fi

# Set the terminal title to the current working directory.
export PS1
_update_ps1u() {
  PS1="\[${bold}\]\D{%c}\n"; # newline
  PS1+='$(r=$?; test $r -ne 0 && echo "\[\e[1;31m\][ret:$r] ")'
  PS1+="\[${userStyle}\]${userName}"; # username
  PS1+="\[${white}\]@"
  PS1+="\[${hostStyle}\]\h"; # host
  PS1+="\[${white}\] in "
  PS1+="\[${green}\]\w"; # working directory
  PS1+='$(__git_ps1 " \[${white}\](%s)")'; # Git repository details
  PS1+="\n"
  PS1+="\[${white}\]\$ \[${reset}\]"; # `$` (and reset color)
}

export PROMPT_COMMAND="_update_ps1u"

export PS2
PS2="\[${yellow}\]→ \[${reset}\]"

# printf "setting bash_prompt\n"
